### ISSUE TITLE
Startup without cmd console window?

### ISSUE THREAD

**Issue by markjfisher** [falkTX/Catia#5]
I run Catia via qjackctl on windows through a startup script using:

    start "Catia" /D "C:\Audio\Cadence-0.8.1" /B /MIN CALL "Catia.exe"

However, despite the "/B" (no window) arg, this always opens a command shell window displaying things like:

```text
PatchCanvas::splitGroup(1) - group is already splitted
PatchCanvas::splitGroup(2) - group is already splitted
PatchCanvas::splitGroup(3) - group is already splitted
PatchCanvas::splitGroup(4) - group is already splitted
PatchCanvas::splitGroup(5) - group is already splitted
PatchCanvas::splitGroup(6) - group is already splitted
... down to 51
```

Is it possible to supress this?

EDIT: Also, is it possible to get a more up to date build of Cadence for Windows? I see 0.9.1 was released nearly 2 years ago, but the download for windows is 0.8.1, which makes trying to look at the code a bit hard as the current version has corrected the spelling mistake of "splitted" to "split".

**Comment by falkTX** [comment]
There are no proper builds of Catia for windows yet. this is yet to be setup.
So until then it is not worth to report things because the entire toolkit has changed (from qt4 to qt5)

**Comment by markjfisher** [comment]
ok, no worries. any timeline on a windows build, or need a volunteer to try it out when you do?

**Comment by falkTX** [comment]
sometime early next year

**Comment by markjfisher** [comment]
ok, I'll close this, it was more an information request than a bug. cheers!
